"""The judge reads the user's messages since the goal was set; newer steering overrides the contract."""

import json
import os
import time

import pytest

from hermes_cli import goals

MERGE_GO = "You can merge on CI green and after all reviews"
CONTINUATION = "[Continuing toward your standing goal]\nGoal: finish the PR"
NOTICE = ("[David Zhang] [IMPORTANT: Background process proc_1 completed normally (exit code 0).]  "
          "[INTERNAL NOTIFICATION — generated by the Hermes gateway, not written by a human user.]")


@pytest.fixture
def manager(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    goals._DB_CACHE.clear()
    mgr = goals.GoalManager("steering-session")
    # The 2026-10-07 record (session 49e59632): an inferred contract carrying invented prohibitions.
    mgr.set("Push the 8 fixes to PR #20647, run the grok review round, report", contract=goals.GoalContract(
        outcome="8 fixes pushed; grok review round run; summary delivered",
        verification="gh pr view 20647 shows the fix commits; CI green",
        constraints="Do not merge the PR or force-push over others' commits",
    ))
    yield mgr
    goals._DB_CACHE.clear()


def _capture(monkeypatch, verdict="done"):
    prompts = []

    def judge(call_llm, system, prompt, timeout):
        prompts.append((system, prompt))
        return json.dumps({"verdict": verdict, "reason": "r"})

    monkeypatch.setattr(goals, "_call_goal_judge_llm", judge)
    return prompts


def test_owner_permission_reaches_the_judge_with_the_override_rule(manager, monkeypatch):
    prompts = _capture(monkeypatch)
    manager.evaluate_after_turn("Merged PR #20647; CI green.", owner_message=MERGE_GO)
    system, prompt = prompts[0]
    assert MERGE_GO in prompt
    assert "newer message wins" in prompt and "explicitly allowed is not a violation" in prompt
    assert prompt.index(MERGE_GO) < prompt.index("Agent's most recent response")
    assert "override it where they conflict" in system
    assert "A later user message that allowed the action lifts that Constraint" in prompt


@pytest.mark.parametrize("text", [CONTINUATION, f"[David Zhang] {CONTINUATION}", NOTICE,
                                  "[Goal heartbeat 1/3 — no session activity for 50m]", "[Heartbeat] tick", "", "   "])
def test_machine_turns_are_not_steering(manager, monkeypatch, text):
    prompts = _capture(monkeypatch, verdict="continue")
    manager.evaluate_after_turn("working", owner_message=text)
    assert manager.state.owner_messages == []
    assert "Messages the user sent after this goal was set" not in prompts[0][1]


def test_no_owner_messages_leaves_the_prompt_unchanged(manager, monkeypatch):
    prompts = _capture(monkeypatch, verdict="continue")
    manager.evaluate_after_turn("working")
    assert "Messages the user sent" not in prompts[0][1]
    assert "Goal:\n" in prompts[0][1] and "\n\nCompletion contract" in prompts[0][1]


def test_steering_persists_is_capped_and_deduped(manager, monkeypatch):
    _capture(monkeypatch, verdict="continue")
    for i in range(goals.OWNER_MESSAGES_MAX + 3):
        manager.evaluate_after_turn("working", owner_message=f"instruction {i}")
    manager.evaluate_after_turn("working", owner_message=f"instruction {goals.OWNER_MESSAGES_MAX + 2}")
    reloaded = goals.GoalManager(manager.session_id).state
    texts = [m["text"] for m in reloaded.owner_messages]
    assert texts == [f"instruction {i}" for i in range(3, goals.OWNER_MESSAGES_MAX + 3)]
    assert all(m["at"] > 0 for m in reloaded.owner_messages)
    assert goals.GoalState.from_json('{"goal":"legacy"}').owner_messages == []


def test_long_messages_are_clipped(manager, monkeypatch):
    _capture(monkeypatch, verdict="continue")
    manager.evaluate_after_turn("working", owner_message="x" * 5000)
    kept = manager.state.owner_messages[0]["text"]
    assert kept.startswith("x" * goals._OWNER_MESSAGE_CHARS) and kept.endswith("[truncated]")
    assert len(kept) < goals._OWNER_MESSAGE_CHARS + 20


def test_steering_sent_during_a_wait_is_kept_for_the_next_judgement(manager, monkeypatch):
    prompts = _capture(monkeypatch, verdict="continue")
    manager.wait_for_seconds(600, reason="CI")
    decision = manager.evaluate_after_turn("waiting on CI", owner_message=MERGE_GO)
    assert not prompts and decision["verdict"] == "waiting"
    assert goals.GoalManager(manager.session_id).state.owner_messages[0]["text"] == MERGE_GO
    manager.stop_waiting()
    manager.evaluate_after_turn("CI green; merged.")
    assert MERGE_GO in prompts[0][1]


def test_a_new_goal_starts_without_old_steering(manager, monkeypatch):
    _capture(monkeypatch, verdict="continue")
    manager.evaluate_after_turn("working", owner_message=MERGE_GO)
    manager.set("Something else")
    assert manager.state.owner_messages == []
